### ISSUE TITLE
fit function of fitter class won't run

### ISSUE THREAD

**Issue by paigemkelly** [sweverett/CluStR#39] opened 2020-09-22 01:06 UTC
the fit function will not run in the fitter class. the output when this is in the main: "fits = Fitter(viable_data, plot_filename)" is only "test1" so it runs the __init__ part then stops. 

class Fitter(object):
    def __init__(self, data, plotting_filename):
        self.viable_data = data
        self.plotting_filename = plotting_filename
        **print('test1')**
    def fit(self):
        **print('test2')**
        x_obs = self.viable_data[0]
        y_obs = self.viable_data[1]
        x_err = self.viable_data[2]
        y_err = self.viable_data[3]
        #run linmix
        print ("Using Kelly Algorithm...")
        kelly_b, kelly_m, kelly_sig = reglib.run_linmix(x_obs, y_obs, x_err, y_err)
        print(kelly_b)
        #use before plotting
        log_x = np.log(x_obs)
        x_piv = np.median(log_x)
        log_y = np.log(y_obs)

        return [log_x-x_piv, log_y, x_err/x_obs, y_err/y_obs, x_piv]

**Comment by sweverett** [comment] 2020-09-22 07:15
That is because you are constructing a `Fitter` object in `main()`, but not calling the `Fitter.fit()` function. You can add a line to `main()` like the following:
```
fitter = Fitter(...)
fitter.fit()
...
```
It will then call the function that `print('test2')` is in.

**Comment by paigemkelly** [comment] 2020-09-22 18:11
Hey spencer, do you think you could try to run the code that’s up now? I’m
getting the error “[Errno 104] connection reset by peer.” Thanks. I’m
wondering if it’s something wrong on my end.

**Comment by sweverett** [comment] 2020-09-22 18:26
That sounds like you're having trouble connecting to a server - are you working through ssh? Having wifi problems?

I won't be able to check this for a while, but can tonight if you still aren't able to.

**Comment by paigemkelly** [comment] 2020-09-22 18:30
I checked everything on my end and can’t find anything wrong. Before the
error there was a lot about linmix so I was wondering if I needed
permission or something to run it. Thanks for your help! I’ll let you know
if Jose or I solve the problem before tonight.

**Comment by sweverett** [comment] 2020-09-22 18:35
Shouldn't have anything to do with linmix. That's very strange.

**Comment by jjobel** [comment] 2020-09-22 22:07
Managed to pull Paige's changes to `clustr.py` and run it on my local computer. There's something popping up that I can't seem to figure out. It's the following error, 
```
Using Kelly Algorithm...
Traceback (most recent call last):
  File "clustr.py", line 241, in <module>
    main()
  File "clustr.py", line 233, in main
    run_fit = fits.fit()
  File "clustr.py", line 202, in fit
    kelly_b, kelly_m, kelly_sig = reglib.run_linmix(x_obs, y_obs, x_err, y_err)
  File "C:\Users\Korosen\CluStR\reglib.py", line 116, in run_linmix
    model = linmix.LinMix(x, y, err_x, err_y, xycov, delta, 2, 2)
  File "C:\Users\Korosen\Anaconda3\envs\clustr\lib\site-packages\linmix\linmix.py", line 402, in __init__
    seed = np.random.randint(2**32-1)
  File "mtrand.pyx", line 628, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1318, in numpy.random.bounded_integers._rand_int32
ValueError: high is out of bounds for int32
``` 
Not completely sure what's going on here, but could it be that the seed value used in the linmix class (line 402 in the linmix.py) is to large? As stated in the error message above. 
So far `clustr.py` stops at `line 202` and outputs that error.

**Comment by sweverett** [comment] 2020-09-23 20:27
This is very strange...are you on a 32 bit machine? Are you in the correct clustr conda environment? linmix expects python 2

**Comment by jjobel** [comment] 2020-09-23 20:36
I'm running on a 64-bit and in the clustr environment. If linmix expects python 2, then I think that's were the problem may lie because I updated python to python 3.7.9 in the clustr environment. Is it possible to revert to python 2?

**Comment by sweverett** [comment] 2020-09-23 20:40
That may be very tricky to fix by hand. Was there a reason you needed to update python? If you don't have a strong need for it, I recommend rebuilding the environment from the yaml file on the master branch of the repo. Instructions should be on the readme.

**Comment by paigemkelly** [comment] 2020-09-23 20:44
I have the environment on my end that you set up with me, and I’m getting
the same error as Jose.

**Comment by paigemkelly** [comment] 2020-09-23 20:46
Actually it might not be the exact same thing, but very similar. I’m not at
my computer to check right now.

**Comment by jjobel** [comment] 2020-09-23 20:46
I think I updated it when I made a change to `import cPickle as pickle` on June 20, 2020. I'll make try rebuilding the environment right now and post an update once I'm done.

**Comment by sweverett** [comment] 2020-09-23 20:49
Are you all working on linux or windows? It looks like this error is sometimes hardware dependent.

**Comment by paigemkelly** [comment] 2020-09-23 20:49
Linux for me

**Comment by jjobel** [comment] 2020-09-23 20:49
I'm working on a Windows 10.

**Comment by sweverett** [comment] 2020-09-23 20:56
Unfortunately I probably won't have time to look at this until tonight. It is very hard for me to help diagnose the problem right now as I am unable to recreate it. If you know how to use the nice python debugger `pudb`, that could help. You should be able to just add the following
```
import pudb
...
pudb.set_trace()
# [linmix call]
```
and then step through the problems with `s` and `n`. If that is too much then these are places to start:
https://github.com/dask/dask-ml/issues/230
https://stackoverflow.com/questions/36797420/easiest-way-to-generate-random-int64-array-in-numpy

**Comment by paigemkelly** [comment] 2020-09-23 21:02
I’ll take a look at that this evening. thanks for your help!

**Comment by jjobel** [comment] 2020-09-23 21:03
Thanks Spencer! We'll check it out. Aslo, there's a way to rollback to a previous environment using `conda list --revisions` to list a history of changes made to the environment and then using `conda install --rev REVNUM` to rollback to a previous version of the environment. I'm going to try it out right now.

**Comment by jjobel** [comment] 2020-09-24 00:38
- Okay I managed to delete the `clustr` environment and rebuild it using the `environment.yml` file from the `rewrite` branch. I had to add on the `conda-forge` channel and change the versions of `matplotlib`, `astropy`, and `scipy` according to which ones can be found in what channel, but they're not huge version changes. I used the Anaconda Cloud [https://anaconda.org/search?q=](url) website to determine in what channel each version lied in.  
- I did this because the `environment.yml` file from the `master` branch wasn't finding the three libraries I mentioned above.
- Now I'm going to run `clustr.py` once I finish setting up the environment.

**Comment by sweverett** [comment] 2020-09-24 15:31
Sorry I haven't been able to be more helpful yet! Another thing you can try is switching over to the master branch and seeing if you can get that to run on your machine. If it does (using the same environment), then that gives us a hint as to what is going on. If it doesn't, then it probably is a hardware or env problem.

**Comment by paigemkelly** [comment] 2020-09-24 20:35
I'm still having trouble setting up the environment with the older versions of things like astropy that I already have installed. I also went on Josh meyers git hub and looked at some of the more recent additions to linmix and 2 years ago he put something up about updates to make python3 work. So I'm not so sure that's the problem. If it's not the issue then we wont have to create an environment that works with python2.

 I printed some of the values for lr500 and lambda. Lambda looked good, but a lot of the values for lr500 were "nan." Could this potentially be the problem? maybe we need to cut those out before it can run? or should it handle that automatically?

**Comment by sweverett** [comment] 2020-09-24 22:48
Hard to say without reproducing the bug myself. I have a little time now. I can switch to your branch, but can you give me the command you are using to run and email me the catalog?

**Comment by sweverett** [comment] 2020-09-24 22:59
Ok, I ran the following:
```
python clustr.py ../tesla/des/y3/matcha/y3a2-6.4.22+2_peak_fixed_maybe_final_merged_no_spaces.fits lambda lr500 param.config
```
And got this warning that has never shown up before, but it did run:
```
error: Kernel is too old for Iris. Consider upgrading to kernel v4.16.

libGL error: failed to create dri screen
libGL error: failed to load driver: iris
error: Kernel is too old for Iris. Consider upgrading to kernel v4.16.

libGL error: failed to create dri screen
libGL error: failed to load driver: iris
```
and produced this plot:
![image](https://user-images.githubusercontent.com/8742179/94208422-a2ddca00-fe7e-11ea-9980-ca687670e615.png)
Do you see any of this when you run?

**Comment by jjobel** [comment] 2020-09-24 23:03
The command is:
`python clustr.py "y3a2-6.4.22+2_peak_fixed_maybe_final_merged.fits" lr2500 lambda param.config`
 
Note: I managed to create a `clustr` environment with python 2  and yes, I do get the graph you just posted. If you remove the hashtags on line in the `def main():`
```
#fitter = Fitter(viable_data) #(6)
#linmixfit = fitter.fit(viable_data)
```
you may be able to reproduce the error `ValueError: high is out of bound for int32` we've been getting.

**Comment by jjobel** [comment] 2020-09-24 23:29
I did as you suggested earlier. I `git clone` the master branch and ran `clustr`. Unfortunately, I get the same error as the one in the rewrite branch. 
```
(clustr) C:\Users\Korosen\Clustr>python clustr.py "y3a2-6.4.22+2_peak_fixed_maybe_final_merged.fits" lambda lr2500 -p jose -m kelly

Checking dependencies...
prefix = jose
prefix = jose

Inputted options: Namespace(catalog='y3a2-6.4.22+2_peak_fixed_maybe_final_merged.fits', flags=None, method='kelly', prefix='jose', x='lr2500', y='lambda')

Grabbing data...
Accepted 205 data out of 1092
mean x error: 3.43195121952496e+54
mean y error: 4.461306292682926

Fitting data...
median log(x-x_piv) = 0.0
Using Kelly Algorithm...
Traceback (most recent call last):
  File "clustr.py", line 556, in <module>
    main()
  File "clustr.py", line 536, in main
    kelly_scaled_fit, mantz_scaled_fit = fit(*scaled_data[:4])
  File "clustr.py", line 320, in fit
    x_obs, y_obs, x_err, y_err
  File "C:\Users\Korosen\Clustr\reglib.py", line 117, in run_linmix
    model = linmix.LinMix(x, y, err_x, err_y, xycov, delta, 2, 2)
  File "C:\Users\Korosen\Anaconda3\envs\clustr\lib\site-packages\linmix\linmix.py", line 402, in __init__
    seed = np.random.randint(2**32-1)
  File "mtrand.pyx", line 990, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32
```
I'm starting to think it may have to do with either our computers or we're missing something. I know the program runs on Spencer's for sure because that's where I got the results for my thesis. 

By the way, I just checked out jmeyers314/linmix github issue page and someone is having this same problem. It was posted July 12, 2020.

**Comment by sweverett** [comment] 2020-09-25 00:27
Ok, I started doing some edits that I promised a long time ago including how to deal with NaNs, flags, etc. It's a decent amount of changes so I suggest looking through the commit (dcd30af73bb958e89a0815fb5888d904e10a7262).

I uncommented the linmix lines and got it running. I added a small plot of the best fit line on top of the data points just for fun:
![image](https://user-images.githubusercontent.com/8742179/94212832-133e1880-fe8a-11ea-8fdd-b57ef8f05b71.png)
(Note: The axis values look weird because it's in ln space, and the x-axis is ln(x)-pivot(x) )

Pull from `rewrite` and try it again. I suspect that it will not, as this looks like a hardware issue, with Windows python defaulting to int32. Not sure why Paige is suddenly having this issue though.

**Comment by sweverett** [comment] 2020-09-25 00:29
(Note: The axis values look weird because it's in ln space, and the x-axis is ln(x)-pivot(x) )

**Comment by jjobel** [comment] 2020-09-25 00:53
Okay thank you Spencer! At first I was getting the same error even though I pulled your changes but after a few minutes of re-reading what you said I figured out how to solve the `ValueError: high is out of bound for int32` using what you suggested about Windows python defaulting to int32. I'll describe how I did it below,
- Go to the `linmix.py` file (the error message itself displays the path to the file) 
- Open the file and go to `line 402`. Should look like this 
``` 
if seed is None:
    seed = np.random.randint(2**32-1)
``` 
- Change the line by adding `dtype=np.int64` as follows:
``` 
if seed is None:
    seed = np.random.randint(2**32-1, dtype=np.int64)
```
- Save the file and try running `clustr` again. 

The above steps worked for me and I was able to reproduce your graph and results @sweverett

**Comment by sweverett** [comment] 2020-09-25 01:02
Great! I'll close this for now, but can reopen if this fix doesn't work for @paigemkelly

**Comment by paigemkelly** [comment] 2020-09-25 16:17
great, thank you so much! so it appears to possibly be working, but it says "running kelly algorithm..." and keeps loading. I tried to run it and restart it several times last night and then left it running all night to see if it would load, and it did not...

**Comment by paigemkelly** [comment] 2020-09-25 17:04
I'm seeing I'm behind on pulls even though when I check the status or try to pull it says I'm up to date. I will try to figure this out and hopefully it runs after that/

**Closed** 2020-09-25 17:58 UTC
